import Head from 'next/head';
import AboutUs from '../sections/AboutUs';
import Hero from '../sections/Hero';

export default function Home() {
  return (
    <>
      <Head>
        <title>| Stolarz | Nazwa Firmy |</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section>
          <Hero />
        </section>
        <section>
          <AboutUs />
        </section>
      </main>
      <footer>
      </footer>
    </>
  );
};
