import Head from 'next/head';
import { useEffect, useState } from 'react';
import RingLoader from "react-spinners/RingLoader";
import styled from 'styled-components';
import { motion } from 'framer-motion';
import ScrollToTop from '../components/ScrollToTop/ScrollToTop';

import AboutUs from '../sections/AboutUs';
import Hero from '../sections/Hero';
import Information from '../sections/Information';
import Specialization from '../sections/Specialization';
import Team from '../sections/Team';
import WhyUs from '../sections/WhyUs';

export default function Home() {
  let [loading, setLoading] = useState(false);

  useEffect(() => {
    setLoading(true);
    const timer = setTimeout(() => {
      setLoading(false);
    }, 2000);
    return () => clearTimeout(timer);
  }, []);
  
  return (
    <>
      <Head>
        <title>| Stolarz | Nazwa Firmy |</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {
          loading ?
            <Loader>
              <RingLoader color={'#F17900'} loading={loading} size={150}/>
            </Loader>
            :
            <motion.div initial="hidden" animate="show">
              <ScrollToTop />
              <section id="home">
                    <Hero/>          
              </section>
              <section id="aboutUs">
                <AboutUs />                
              </section>
              <section id="specialization">
                <Specialization />
              </section>
              <section id="whyUs">
                <WhyUs />           
              </section>
              <section id="team">
                <Team />
              </section>
              <section id="information">
                <Information />
              </section>
            </motion.div>
        }
      </main>
    </>
  );
};


const Loader = styled.div`
  text-align: center;
  display: flex;
  justify-content: center;
  align-items: center;
  width: 100%;
  height: 100vh;
  background-color: #1d3557;
`;
