import Head from 'next/head';
import { useEffect, useState } from 'react';
import RingLoader from "react-spinners/RingLoader";
import styled from 'styled-components';

import AboutUs from '../sections/AboutUs';
import Hero from '../sections/Hero';

export default function Home() {
  let [loading, setLoading] = useState(false);

  useEffect(() => {
    setLoading(true);
    const timer = setTimeout(() => {
      setLoading(false);
    }, 2000);
    return () => clearTimeout(timer);
  }, []);
  
  return (
    <>
      <Head>
        <title>| Stolarz | Nazwa Firmy |</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {
          loading ?
            <Loader>
              <RingLoader color={'#F17900'} loading={loading} size={150}/>
            </Loader>
            :
            <>
              <Hero />
              <AboutUs />
            </>
        }
      </main>
    </>
  );
};


const Loader = styled.div`
  text-align: center;
  display: flex;
  justify-content: center;
  align-items: center;
  width: 100%;
  height: 100vh;
  background-color: #1d3557;
`;
